### ISSUE TITLE
Add a note how to use

### ISSUE THREAD

**Issue by Karmelicka** [Endiasz/Instaling-Bot#1]
Siema oddałbyś info jak tego użyć 😅

**Comment by Endiasz** [comment]
Spróbuję to jakoś opisać

**Comment by Karmelicka** [comment]
Bot się zatrzymuje na pierwszym tłumaczeniu i tak w kółko, chyba robię coś nie tak

**Comment by Endiasz** [comment]
Przekopiuj albo daj zdjęcie z konsoli, może coś się dowiem

**Comment by Karmelicka** [comment]
![image](https://user-images.githubusercontent.com/76181040/142238127-f6e0d48e-7cd0-49f6-877e-e78965aab8ce.png)

**Comment by Endiasz** [comment]
Hmmm... Korzystasz może z Chrome, ja wszystko testowałem na Chrome. Nie mogę odtworzyc twojego problemu, nie mam pojęcia czemu tak się dzieje

**Comment by Karmelicka** [comment]
Tak, chrome i dzieje sie coś takiego że jakby bot próbuje skanować słówka ale cały czas od instalinga dostaje jedno i to samo i się zapętla bo nie ma nowych słówek.

**Comment by Endiasz** [comment]
Po tym jak wygenerował losowe słówko to powinien sobie kliknąć żeby przeszło do kolejnej strony właśnie, później będę miał więcej czasu to popatrzę o co chodzi

**Comment by Endiasz** [comment]
Wrzuciłem trochę nowszą wersję teraz może będzie działało. Jak wrzucisz nowe pliki do pliku rozszerzenia to ważne żeby odświeżyć rozszerzenie więcej narzędzi > rozszerzenia i ikonka odświeżenie przy okienku bota, jak strona instalinga była otwarta to też trzeba odświeżyć kartę.

**Comment by Endiasz** [comment]
Chyba w jakiś sposób udało mi się odtworzyć twój błąd. Chyba jakiś problem instaling ma z połączeniem

**Comment by Endiasz** [comment]
V2 Udało mi się odtworzyć błąd jednak coś bot nie wykrywa że jest już słówko wpisane i że ma coś innego zrobić

**Comment by Karmelicka** [comment]
Siema, czasem po wklepaniu słówka nie uczy się nowego i błądzi w pętli próbując wpisać cokolwiek i tak dalej

**Comment by Karmelicka** [comment]
Już wiem dlaczego, przejrzałem kod i to co się wyświetla na stronie i czasem jest tak że nie ma tego tzw glośnika i jeśli go nie ma to bot nie wie co robic

**Comment by Endiasz** [comment]
z tym głośniczkiem do strasznie łopatologicznie zrobiłem, same początki i nie wiedziałem co z czym. Za chwilę poprawię na lepszy sposób sprawdzania. Ale dalej łopatologicznie

**Comment by Endiasz** [comment]
Zrobiłem teraz to w sposób który już nie powinien generować tego błędu.

**Comment by Karmelicka** [comment]
Wiem, ja już wczoraj sobie naprawiłem i mi śmigało

**Comment by Karmelicka** [comment]
Możesz ustawić repo na prywatne
