### ISSUE TITLE
Translations bug

### ISSUE THREAD

**Issue by THEzombiePL** [Endiasz/Instaling-Bot#3]
### Co nie działa:
Czasami zdarzy się, że jedno słowo ma 2 tłumaczenia, a jest zapisane tylko jedno. Np. festival - Festival | Festspiele

### Jak pozbyć się tego błędu?
Zmienić sposób zapisu danych tak, aby dodawać każde poprawne tłumaczenie do listy i przy sprawdzaniu losowo wybierać na podstawie "klucza".

**Comment by Endiasz** [comment]
O ilę dobrze rozumiem, to jeżeli jest dane słówko to i tak zalicza poprawnie, czy jest problem że nie zalicza

**Comment by Endiasz** [comment]
Osoboście mi się wydaje że powinno i tak zaliczyć, a jak tak jest to wydaję mi się że nie ma czym sie przejmować, chyba że to drugie tłumaczenie jest wymagane
